### ISSUE TITLE
请问这个怎么在node cnpm下正常运行起来？

### ISSUE THREAD

**Issue by robyle** [run27017/vue-chat#1]

**Comment by run27017** [comment]
node 下的 cnpm 也就是 npm 吧，你先要创建一个 vue 项目：

```bash
npm install --global vue
vue create my-app
```

然后在项目下添加我的包：

```bash
npm install -D @run27017/vue-chat
```

最后就可以本项目 README 提示的步骤引入组件了。

**Comment by robyle** [comment]
> node 下的 cnpm 也就是 npm 吧，你先要创建一个 vue 项目：
> 
> ```shell
> npm install --global vue
> vue create my-app
> ```
> 
> 然后在项目下添加我的包：
> 
> ```shell
> npm install -D @run27017/vue-chat
> ```
> 
> 最后就可以本项目 README 提示的步骤引入组件了。

你好，我按您的说明实践了下，编译还是报错。

![QQ截图20201218102758](https://user-images.githubusercontent.com/11662528/102567153-dea1cc00-411b-11eb-9a9f-95e52e6717af.png)

您看  方便帮忙再看是什么原因么，我的运行环境是基于一个最小的uniapp 运行的Demo缓解跑的。

**Comment by robyle** [comment]
10:26:00.479 请注意运行模式下，因日志输出、sourcemap以及未压缩源码等原因，性能和包体积，均不及发行模式。
10:26:00.508 正在编译中...
10:26:34.266 App平台 v3 模式暂不支持在 js 文件中引用"@run27017/vue-chat/dist/chat.css" 请改在 style 内引用
10:26:39.509  DONE  Build complete. Watching for changes...
10:26:39.510 项目 'DefaultDemo' 编译成功。
10:26:40.719 正在建立手机连接...
10:26:41.798 手机端调试基座版本号为2.9.8，版本号相同，跳过基座更新
10:26:42.025 正在同步手机端程序文件...
10:26:44.402 同步手机端程序文件完成
10:26:44.555 正在启动HBuilder调试基座...
10:26:48.545 如手机上HBuilder调试基座未启动，请手动启动...
10:26:48.902 reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Uncaught TypeError: Cannot read property 'querySelector' of undefined

**Comment by run27017** [comment]
uniapp 的系统环境我不太熟悉，你先试一下一般的浏览器环境是否可以跑得通吧。
